name: Push into master workflow

on:
  push:
    branches:
      - master
      - develop

env:
  DOTNET_VERSION: '9.0'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Add GitHub Packages source
        run: dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --name "github" --username ${{ github.repository_owner }} --password ${{ secrets.API_KEY }} --store-password-in-clear-text

      - name: Restore
        run: dotnet restore

      - name: Code format
        run: dotnet format

      - name: Pack NuGet package
        run: dotnet pack --configuration Release -o ./nupkg

      - name: Publish NuGet package
        run: |
          dotnet nuget push ./nupkg/*.nupkg \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key ${{ secrets.API_KEY }}